FROM 763104351884.dkr.ecr.us-east-1.amazonaws.com/huggingface-pytorch-inference:1.10.2-transformers4.17.0-gpu-py38-cu113-ubuntu20.04 as gpu_base-inf

ADD requirements.txt .

RUN pip install -r requirements.txt

ADD mod_handler_service.py /opt/conda/lib/python3.8/site-packages/sagemaker_huggingface_inference_toolkit/handler_service.py

EXPOSE 8080 8081
ENTRYPOINT ["python", "/usr/local/bin/dockerd-entrypoint.py"]
CMD ["serve"]