# Model arguments
model_name_or_path: Qwen/Qwen3-4B
tokenizer_name_or_path: Qwen/Qwen3-4B
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
use_liger: false
bf16: true
tf32: true
output_dir: runs/spectrum-Qwen-3-4B

# Dataset arguments
dataset_id_or_path: ../DPO/data/nvidia_When2Call_train_sft.json
max_seq_length: 2048
packing: true

# Spectrum arguments
spectrum_config_path: /home/sagemaker-user/DPO/spectrum-layer/snr_results_Qwen-Qwen3-4B_unfrozenparameters_50percent.yaml

# Training arguments
num_train_epochs: 50
per_device_train_batch_size: 4
gradient_accumulation_steps: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: true
learning_rate: 5.0e-5
lr_scheduler_type: cosine
warmup_ratio: 0.1

# Logging arguments
logging_strategy: steps
logging_steps: 5
report_to:
- wandb
save_strategy: "no" # "epoch"
seed: 42

# Hugging Face Hub 
push_to_hub: false
# hub_model_id: llama-3-1-8b-math-orca-qlora-10k-ep1 # if not defined same as output_dir
hub_strategy: every_save